// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0M2A9umIRhKYcMEE767LiOsFgsYathF4',
    appId: '1:486962914:web:d84d152778379cd31750bb',
    messagingSenderId: '486962914',
    projectId: 'healthudy',
    authDomain: 'healthudy.firebaseapp.com',
    storageBucket: 'healthudy.firebasestorage.app',
    measurementId: 'G-15B6PX8TW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuHAZXJPzQiyOsmw1EiXHSbH6v8VYnYM4',
    appId: '1:486962914:android:3e01f2a3c39a9b911750bb',
    messagingSenderId: '486962914',
    projectId: 'healthudy',
    storageBucket: 'healthudy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDJUi8bbhPQn1kksF-yXEcXdtDKLBqTj8',
    appId: '1:486962914:ios:9281e31da05b10dc1750bb',
    messagingSenderId: '486962914',
    projectId: 'healthudy',
    storageBucket: 'healthudy.firebasestorage.app',
    iosBundleId: 'com.example.healthudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDJUi8bbhPQn1kksF-yXEcXdtDKLBqTj8',
    appId: '1:486962914:ios:9281e31da05b10dc1750bb',
    messagingSenderId: '486962914',
    projectId: 'healthudy',
    storageBucket: 'healthudy.firebasestorage.app',
    iosBundleId: 'com.example.healthudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0M2A9umIRhKYcMEE767LiOsFgsYathF4',
    appId: '1:486962914:web:b3d1760b720ff52a1750bb',
    messagingSenderId: '486962914',
    projectId: 'healthudy',
    authDomain: 'healthudy.firebaseapp.com',
    storageBucket: 'healthudy.firebasestorage.app',
    measurementId: 'G-2NJPDLV6DW',
  );
}
